# Generated by Django 4.2 on 2023-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('sdgs', models.CharField(max_length=30)),
                ('directors', models.IntegerField()),
                ('members', models.IntegerField()),
                ('funding', models.CharField(max_length=30)),
            ],
        ),
    ]
